# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6616aa13fe118e38eeb39ad28ff7e4888ff1beb2f3ecef27aca2c8793185112b42da06d2e284b9556efae5daa07ab51db9a9d9899b7273aaeaf7683e3a7c84fb

test:
  secret_key_base: 76bf7925731adff9bccae083fcf8e8cb233dfb394690aebcb3d54fa00289fea0ec37e0a32a85d35f0469296b920dcb93f26ebdd7da0671e21df9eca12b950d0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
